# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create and Checkout gh-pages Branch
      run: |
        git config user.name "nvkhuy"
        git config user.email "khanhhuynguyenvu@gmail.com"
        git checkout --orphan gh-pages
        git rm -rf .
        git clean -fxd
        git checkout main -- _site/* # Copy the contents of _site from the main branch
        git mv _site/* .
        rm -r _site
        git add .
        git commit -m "Deploy Jekyll site to gh-pages"
        git push origin gh-pages
      with:
        github_token: ${{ secrets.NVKHUY_BOT_TOKEN }}

    - name: Clean up
      run: |
        git checkout main
        git branch -D gh-pages
      with:
        github_token: ${{ secrets.NVKHUY_BOT_TOKEN }}
